In [1]:
import pathlib
import os
if not "changed_working_directory" in locals():
    changed_working_directory = True
    os.chdir(pathlib.Path().resolve().parent)
    
%load_ext autoreload
%autoreload 2

import pandas as pd

from src import constants as const
dataset_train_path = os.path.join(const.dir.data(), "df_adult_edited_train.csv")
dataset_test_path = os.path.join(const.dir.data(), "df_adult_edited_test.csv")

data_train = pd.read_csv(dataset_train_path)
data_test = pd.read_csv(dataset_test_path)
discrete_columns = data_train.columns[data_train.dtypes == "object"]

imports_path = "src//imports.ipynb"

%run "$imports_path"

In [4]:
import pandas as pd
import numpy
creditcard = pd.read_csv(os.path.join(const.dir.data(), "comparison", "creditcard.csv"))
print("hei")
creditcard_edited = creditcard
creditcard_edited.loc[:, "Class"] = "Class" + creditcard.loc[:, "Class"].astype("string")
print("hei2")
creditcard_edited
creditcard_edited.to_csv(os.path.join(const.dir.data(), "comparison", "creditcard_edited.csv"), index=False)

hei
hei2

In [72]:
import pandas as pd
import numpy
covtype = pd.read_csv(os.path.join(const.dir.data(), "comparison", "covtype.csv"))
covtype_edited = covtype.iloc[:, ~ covtype.columns.str.contains("^(Soil_Type|Wilderness_Area)", regex=True)]
covtype_edited.insert(0, "Soil_Type", covtype.loc[:, covtype.columns.str.startswith("Soil_Type")].idxmax(axis=1))
covtype_edited.insert(0, "Wilderness_Area", covtype.loc[:, covtype.columns.str.startswith("Wilderness_Area")].idxmax(axis=1))
covtype_edited.loc[:, "Cover_Type"] = "CoverType" + covtype.loc[:, "Cover_Type"].astype("string")
covtype_edited.to_csv(os.path.join(const.dir.data(), "comparison", "covtype_edited.csv"), index=False)
covtype_edited

,Wilderness_Area,Soil_Type,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Cover_Type
0,Wilderness_Area1,Soil_Type29,2596,51,3,258,0,510,221,232,148,6279,CoverType5
1,Wilderness_Area1,Soil_Type29,2590,56,2,212,-6,390,220,235,151,6225,CoverType5
2,Wilderness_Area1,Soil_Type12,2804,139,9,268,65,3180,234,238,135,6121,CoverType2
3,Wilderness_Area1,Soil_Type30,2785,155,18,242,118,3090,238,238,122,6211,CoverType2
4,Wilderness_Area1,Soil_Type29,2595,45,2,153,-1,391,220,234,150,6172,CoverType5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
581007,Wilderness_Area3,Soil_Type2,2396,153,20,85,17,108,240,237,118,837,CoverType3
581008,Wilderness_Area3,Soil_Type2,2391,152,19,67,12,95,240,237,119,845,CoverType3
581009,Wilderness_Area3,Soil_Type2,2386,159,17,60,7,90,236,241,130,854,CoverType3
581010,Wilderness_Area3,Soil_Type2,2384,170,15,60,5,90,230,245,143,864,CoverType3
581011,Wilderness_Area3,Soil_Type2,2383,165,13,60,4,67,231,244,141,875,CoverType3

In [58]:
import pandas as pd
import numpy
news = pd.read_csv(os.path.join(const.dir.data(), "comparison", "OnlineNewsPopularity.csv"))
news.columns = [column.strip() for column in news.columns]
news_edited = news.loc[:, ~ news.columns.str.contains("^(weekday_is|data_channel)")]
news_edited = news_edited.drop("url", axis=1)
news_edited.insert(
    0, "weekday",
    news.loc[:, news.columns.str.contains("^weekday_is")].idxmax(axis=1).str.replace("weekday_is_", "").str.title()
)
news_edited.insert(0, "data_channel",
                   news.loc[:, news.columns.str.contains("^data_channel")].idxmax(axis=1).str.replace("data_channel_is_", ""))
#news_edited.loc[:, "Class"] = "Class" + news.loc[:, "Class"].astype("string")
news_edited.loc[:, "is_weekend"] = np.where(news_edited.loc[:, "is_weekend"] > 0.5, "yes", "no")
news_edited.to_csv(os.path.join(const.dir.data(), "comparison", "news_edited.csv"), index=False)
news_edited

,data_channel,weekday,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,entertainment,Monday,731.0,12.0,219.0,0.663594,1.0,0.815385,4.0,2.0,...,0.100000,0.70,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,bus,Monday,731.0,9.0,255.0,0.604743,1.0,0.791946,3.0,1.0,...,0.033333,0.70,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,bus,Monday,731.0,9.0,211.0,0.575130,1.0,0.663866,3.0,1.0,...,0.100000,1.00,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,entertainment,Monday,731.0,9.0,531.0,0.503788,1.0,0.665635,9.0,0.0,...,0.136364,0.80,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,1200
4,tech,Monday,731.0,13.0,1072.0,0.415646,1.0,0.540890,19.0,19.0,...,0.033333,1.00,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39639,tech,Wednesday,8.0,11.0,346.0,0.529052,1.0,0.684783,9.0,7.0,...,0.100000,0.75,-0.260000,-0.500,-0.125000,0.100000,0.000000,0.400000,0.000000,1800
39640,socmed,Wednesday,8.0,12.0,328.0,0.696296,1.0,0.885057,9.0,7.0,...,0.136364,0.70,-0.211111,-0.400,-0.100000,0.300000,1.000000,0.200000,1.000000,1900
39641,lifestyle,Wednesday,8.0,10.0,442.0,0.516355,1.0,0.644128,24.0,1.0,...,0.136364,0.50,-0.356439,-0.800,-0.166667,0.454545,0.136364,0.045455,0.136364,1900
39642,world,Wednesday,8.0,6.0,682.0,0.539493,1.0,0.692661,10.0,1.0,...,0.062500,0.50,-0.205246,-0.500,-0.012500,0.000000,0.000000,0.500000,0.000000,1100
39643,entertainment,Wednesday,8.0,10.0,157.0,0.701987,1.0,0.846154,1.0,1.0,...,0.100000,0.50,-0.200000,-0.200,-0.200000,0.333333,0.250000,0.166667,0.250000,1300

In [73]:
import sklearn.model_selection
import helpers
covtype_train, covtype_test = sklearn.model_selection.train_test_split(covtype_edited, train_size=0.7)
metrics, cats = helpers.eval.fit_and_evaluate_xgboost(covtype_train, covtype_test, response_col="Cover_Type",
                                                    retcats=True, metrics=["accuracy", "f1"])
metrics

{'accuracy': 0.8679318891132733, 'f1': 0.864395949616608}

In [76]:
from tabGAN import TabGAN
tg_qtr_covertype = TabGAN(covtype_train, batch_size=500, ctgan=True, n_critic=10, adam_beta1 = 0.5,
                 quantile_transformation_int=True, quantile_rand_transformation=True, qtr_spread=1,
                 activation_function="mish", jit_compile=True, qt_n_subsample=int(1e5))

In [77]:
tg_qtr_covertype.train(100, progress_bar=True)

  0%|          | 0/100 [00:00<?, ?it/s]

()

In [ ]:
metrics= helpers.eval.fit_and_evaluate_xgboost(tg_qtr_covertype.sample(), covtype_test, response_col="Cover_Type",
                                                      metrics=["accuracy","f1"])
metrics

In [63]:
import sklearn.model_selection
import helpers

def transform_news_dataset(news):
    return news.assign(shares = lambda x: np.where(x.shares > 3395, "Popular", "Unpopular"))

news_train, news_test = sklearn.model_selection.train_test_split(news_edited, train_size=0.7)
metrics, cats = helpers.eval.fit_and_evaluate_xgboost(news_train, news_test, response_col="shares",
                                                    retcats=True, metrics=["accuracy","auc", "f1", "f1_0", "f1_1"],
                                                     data_transform=transform_news_dataset)
metrics

{'accuracy': 0.7822431478056163,
 'auc': 0.696546519173163,
 'f1': 0.5448307732533701,
 'f1_0': 0.21610169491525424,
 'f1_1': 0.873559851591486}

In [67]:
from tabGAN import TabGAN
tg_qtr = TabGAN(news_edited, batch_size=500, ctgan=True, n_critic=10, adam_beta1 = 0.5,
                 quantile_transformation_int=True, quantile_rand_transformation=True, qtr_spread=1,
                 activation_function="mish", jit_compile=True, qt_n_subsample=int(1e5))

In [68]:
tg_qtr.train(300, progress_bar=True)

  0%|          | 0/300 [00:00<?, ?it/s]

()

In [69]:
metrics= helpers.eval.fit_and_evaluate_xgboost(tg_qtr.sample(), news_test, response_col="shares",
                                                      metrics=["accuracy","auc", "f1", "f1_0", "f1_1"],
                                                     data_transform=transform_news_dataset)
metrics

{'accuracy': 0.7758533714477888,
 'auc': 0.6786496962161391,
 'f1': 0.5317121734026065,
 'f1_0': 0.19358741681790684,
 'f1_1': 0.869836929987306}

In [153]:
print(np.mean(news_test["shares"]))
print("squared root mse mean model:", np.sqrt(np.mean((news_test["shares"] - np.mean(news_test["shares"]))**2)))
print("mae mean model:", np.mean(np.abs((news_test["shares"] - np.mean(news_test["shares"])))))

3336.109298806121
squared root mse mean model: 9874.951863300326
mae mean model: 3108.874500608738

In [152]:
np.sqrt(125855907)

11218.551911900217

In [ ]:
sklearn.metrics.precision_recall_curve([0,1,0,1], [0.2, 0.1, 0.5, 0.2])

In [70]:
import sklearn.model_selection
import helpers
creditcard_train, creditcard_test = sklearn.model_selection.train_test_split(creditcard_edited, train_size=0.7)
metrics, cats_creditcard = helpers.eval.fit_and_evaluate_xgboost(creditcard_train, creditcard_test, response_col="Class",
                                                    retcats=True, metrics=["accuracy", "auc", "f1", "f1_1", "f1_0"])
metrics

{'accuracy': 0.9997191109862715,
 'auc': 0.9929641012406859,
 'f1': 0.9530546723905526,
 'f1_0': 0.9998593447811053,
 'f1_1': 0.90625}

In [54]:
from tabGAN import TabGAN
tg_qtr = TabGAN(creditcard, batch_size=500, ctgan=True, n_critic=10, adam_beta1 = 0.5,
                 quantile_transformation_int=True, quantile_rand_transformation=True, qtr_spread=1,
                 activation_function="mish", jit_compile=True, qt_n_subsample=int(1e5))

In [ ]:
tg_qtr.train(300, progress_bar=True)

In [53]:
helpers.eval.fit_and_evaluate_xgboost(tg_qtr.sample(), creditcard_test, response_col="Class",
                                                    categories=cats_creditcard,
                                      metrics=["accuracy", "auc", "f1", "f1_1", "f1_0"])

{'accuracy': 0.9993094811745842,
 'auc': 0.978457465762715,
 'f1': 0.9005004704141226,
 'f1_0': 0.9996541394814437,
 'f1_1': 0.8013468013468015}